### ISSUE TITLE
Error with new osmdata version 0.2.1

### ISSUE THREAD

**Issue by mpadge** [GIScience/ohsome-r#12]
Hi there, I'm the author of the `osmdata` package, and have just received notification from CRAN that the latest `osmdata` update breaks this package. The full report says:
```
Package check result: OK

Changes to worse in reverse depends:

Package: ohsome
Check: re-building of vignette outputs
New result: ERROR
  Error(s) in re-building vignettes:
    ...
  --- re-building ‘ohsome.Rmd’ using rmarkdown
  Quitting from lines 93-94 (ohsome.Rmd) 
  Error: processing vignette ‘ohsome.Rmd’ failed with diagnostics:
  Error in the HTTP2 framing layer
  --- failed re-building ‘ohsome.Rmd’
  
  SUMMARY: processing the following file failed:
    ‘ohsome.Rmd’
  
  Error: Vignette re-building failed.
  Execution halted
```
I can't reproduce this error at all, so have sent CRAN a link to this issue, and told them that this seems to be a false positive. Let me know if there is indeed anything I can do to help.

**Comment by ofr1tz** [comment]
Hi Mark, thanks for reaching out! 

I can't reproduce that either. `ohsome` only uses `osmdata::getbb("Kigali")` in its vignette and its README. I don't see any change of behaviour in `osmdata::getbb()` that would explain an error? I guess this is a false positive on the reverse dependency check indeed.

**Comment by mpadge** [comment]
Yes, it does seem so indeed. The windows build of osmdata 0.2.1 is now on CRAN, and that error does not arise, so I'm pretty sure we can close and ignore this. Thanks!
