### ISSUE TITLE
Bug on timeout?

### ISSUE THREAD

**Issue by maze2point0** [GIScience/ohsome-r#6]
Hi, 

tried to run the following code chunk to fetch hospitals in Germany. 
Runtime close to 600sec / 10min which is the timeout of the public API. 
I think the response json can not be properly parsed then. 
Can someone verify?

```r
library(rgeoboundaries)
library(ohsome)
ger <- gb_adm0("Germany")

q <- ohsome_query("elements/geometry", 
       ger,
       filter="amenity=hospital")
system.time(
hospitals <- ohsome_post(q)
)
Error: parse error: after array element, I expect ',' or ']'
          22-05-08T20:00:00Z"     }   }{   "timestamp" : "2022-05-17T0
                     (right here) ------^
In addition: Warning message:
Time parameter is not defined and defaults to latest available timestamp within the underlying OSHDB. You can use set_time() to set the time parameter. 
Timing stopped at: 0.683 0.458 647.9
```

**Comment by ofr1tz** [comment]
Thanks for sharing the issue.

This does not seem to be related to timeout, as all non-200 status responses of the ohsome API should result in stopping `ohsome_post()` with an error before attempting to parse the content.

I got a status 200 response with GeoJSON content within 10 min from your example query, but parsing failed with the same error message. Will have to examine further for the actual problem.
